CREATE TYPE "ProspectStatus" AS ENUM ('NEW', 'ASSIGNED', 'CONTACTED', 'QUALIFIED', 'WON', 'LOST', 'DNC');
CREATE TYPE "CampaignStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED');
CREATE TYPE "OpportunityStage" AS ENUM ('DISCOVERY', 'PROPOSAL', 'FOLLOW_UP', 'WON', 'LOST');
ALTER TABLE "Call" ADD COLUMN "campaignId" TEXT, ADD COLUMN "consentConfirmed" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "prospectId" TEXT;
ALTER TABLE "User" ADD COLUMN "teamId" TEXT;
CREATE TABLE "Team" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Team_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Campaign" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL DEFAULT '', "direction" TEXT NOT NULL DEFAULT 'OUTBOUND', "status" "CampaignStatus" NOT NULL DEFAULT 'DRAFT', "teamId" TEXT NOT NULL, "managerId" TEXT, "playbookId" TEXT, "dailyCallGoal" INTEGER NOT NULL DEFAULT 20, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Campaign_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Prospect" ("id" TEXT NOT NULL, "businessName" TEXT NOT NULL, "contactName" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT '', "phone" TEXT NOT NULL, "email" TEXT NOT NULL DEFAULT '', "businessType" TEXT NOT NULL DEFAULT '', "currentProvider" TEXT NOT NULL DEFAULT '', "monthlyVolumeUSD" DOUBLE PRECISION NOT NULL DEFAULT 0, "terminalCount" INTEGER NOT NULL DEFAULT 0, "objective" TEXT NOT NULL DEFAULT '', "mainPainPoint" TEXT NOT NULL DEFAULT '', "address" TEXT NOT NULL DEFAULT '', "tags" TEXT[], "status" "ProspectStatus" NOT NULL DEFAULT 'NEW', "campaignId" TEXT NOT NULL, "assigneeId" TEXT, "attempts" INTEGER NOT NULL DEFAULT 0, "lastContactedAt" TIMESTAMP(3), "doNotCall" BOOLEAN NOT NULL DEFAULT false, "consentStatus" TEXT NOT NULL DEFAULT 'UNKNOWN', "consentAt" TIMESTAMP(3), "consentSource" TEXT NOT NULL DEFAULT '', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Prospect_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Opportunity" ("id" TEXT NOT NULL, "prospectId" TEXT NOT NULL, "stage" "OpportunityStage" NOT NULL DEFAULT 'DISCOVERY', "estimatedValue" DOUBLE PRECISION NOT NULL DEFAULT 0, "expectedCloseAt" TIMESTAMP(3), "notes" TEXT NOT NULL DEFAULT '', "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Opportunity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CrmTask" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "dueAt" TIMESTAMP(3) NOT NULL, "completedAt" TIMESTAMP(3), "ownerId" TEXT NOT NULL, "prospectId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CrmTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ComplianceSettings" ("id" TEXT NOT NULL, "jurisdiction" TEXT NOT NULL, "timezone" TEXT NOT NULL DEFAULT 'America/New_York', "callingStartHour" INTEGER NOT NULL DEFAULT 9, "callingEndHour" INTEGER NOT NULL DEFAULT 20, "retentionDays" INTEGER NOT NULL DEFAULT 365, "requireConsent" BOOLEAN NOT NULL DEFAULT true, "recordingEnabled" BOOLEAN NOT NULL DEFAULT false, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ComplianceSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DncEntry" ("id" TEXT NOT NULL, "phone" TEXT NOT NULL, "reason" TEXT NOT NULL, "source" TEXT NOT NULL DEFAULT 'MANUAL', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DncEntry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "actorId" TEXT NOT NULL, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Campaign_teamId_status_idx" ON "Campaign"("teamId", "status");
CREATE INDEX "Prospect_campaignId_status_idx" ON "Prospect"("campaignId", "status");
CREATE INDEX "Prospect_assigneeId_status_idx" ON "Prospect"("assigneeId", "status");
CREATE INDEX "Prospect_phone_idx" ON "Prospect"("phone");
CREATE UNIQUE INDEX "Opportunity_prospectId_key" ON "Opportunity"("prospectId");
CREATE INDEX "CrmTask_ownerId_dueAt_idx" ON "CrmTask"("ownerId", "dueAt");
CREATE UNIQUE INDEX "ComplianceSettings_jurisdiction_key" ON "ComplianceSettings"("jurisdiction");
CREATE UNIQUE INDEX "DncEntry_phone_key" ON "DncEntry"("phone");
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType", "entityId");
CREATE INDEX "Call_prospectId_createdAt_idx" ON "Call"("prospectId", "createdAt");
CREATE INDEX "Call_campaignId_createdAt_idx" ON "Call"("campaignId", "createdAt");
CREATE INDEX "User_teamId_idx" ON "User"("teamId");
ALTER TABLE "User" ADD CONSTRAINT "User_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_playbookId_fkey" FOREIGN KEY ("playbookId") REFERENCES "Playbook"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Prospect" ADD CONSTRAINT "Prospect_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Prospect" ADD CONSTRAINT "Prospect_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_prospectId_fkey" FOREIGN KEY ("prospectId") REFERENCES "Prospect"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmTask" ADD CONSTRAINT "CrmTask_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CrmTask" ADD CONSTRAINT "CrmTask_prospectId_fkey" FOREIGN KEY ("prospectId") REFERENCES "Prospect"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Call" ADD CONSTRAINT "Call_prospectId_fkey" FOREIGN KEY ("prospectId") REFERENCES "Prospect"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Call" ADD CONSTRAINT "Call_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;
